# Generated by Django 6.0.3 on 2026-04-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options_productvariation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Дополнительное фото', 'verbose_name_plural': 'Галерея фотографий'},
        ),
    ]
