# Generated by Django 6.0.3 on 2026-04-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_orderitem'),
        ('shop', '0004_alter_product_options_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер/Диаметр'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер/Диаметр'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
